name: C++ Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - name: Install dependencies
      run: |
        sudo pip3 install cogapp scons
    - name: Build unit tests
      run: |
        scons
    - name: Run unit tests
      run: |
        scons --test
    - name: Install coverage dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcov lcov
    - name: Running coverage
      run: |
        scons --coverage
    - name: Building coverage report
      uses: manar.benkraoda/lcov-reporter-action@v0.3.5.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: coverage.info

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - uses: actions/setup-python@v2
      name: Install Python
    - name: Install dependencies
      run: |
        pip3 install cogapp scons
    - name: Build unit tests
      run: |
        scons
    - name: Run unit tests
      run: |
        scons --test

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - uses: actions/setup-python@v2
      name: Install Python
    - name: Install dependencies
      run: |
        pip3 install cogapp scons
    - name: Build unit tests
      run: |
        scons
    - name: Run unit tests
      run: |
        scons --test
