name: C++ Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - name: Install dependencies
      run: |
        sudo pip install cogapp
        sudo apt-get update && sudo apt-get -y install scons
    - name: Build unit tests
      run: |
        scons
    - name: Run unit tests
      run: |
        scons --test
