name: macos

on: [push, pull_request]

jobs:

  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - uses: actions/setup-python@v2
      name: Install Python
    - name: Install dependencies
      run: |
        pip3 install cogapp scons
    - name: Build
      run: |
        scons
    - name: Run unit tests
      run: |
        scons --test
